### PR TITLE
linux: set: peer: Add UpdateOnly flag

### PR DESCRIPTION
**Pull request by ernestask**
It is simply missing.

### CODE REVIEW

**Review by gluxon — APPROVED** [review]
Looks great. Thanks!

**Comment by gluxon** [comment]
@ernestask Had to make some modifications to the GitHub actions workflow to run tests. I rebased the pull request for that change.

Would you prefer to fix the formatting errors, or pass it off to me? I'm happy with either option.

**Comment by ernestask** [comment]
I don’t mind doing it. Formatting Rust is something I always forget. :|

**Comment by gluxon** [comment]
This was great. Thanks so much!

**Comment by gluxon** [comment]
2.0.3 just published https://crates.io/crates/wireguard-uapi

**Pull request merged**
